services:
  db:
    image: postgres:18
    container_name: drones
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: postgres
      POSTGRES_DB: drone_telemetry
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: